language: node_js
node_js: 
- 12.6.0
cashe: npm
instal:
  - yarn install
  - cypress install
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/
  on: 
    branch: main